spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bishe
    username: root
    password: 123456wjf

  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB
